//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salt_web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class salt_entities : DbContext
    {
        public salt_entities()
            : base("name=salt_entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<MenuUSState> MenuUSStates { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
    }
}
