//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salt_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_Users
    {
        public aspnet_Users()
        {
            this.aspnet_Roles = new HashSet<aspnet_Roles>();
        }
    
        public System.Guid ApplicationId { get; set; }
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string LoweredUserName { get; set; }
        public string Initials { get; set; }
        public string MobileAlias { get; set; }
        public bool IsAnonymous { get; set; }
        public System.DateTime LastActivityDate { get; set; }
        public string OldID { get; set; }
        public Nullable<System.DateTime> DOH { get; set; }
        public Nullable<System.DateTime> LDE { get; set; }
        public Nullable<System.Guid> Manager { get; set; }
        public Nullable<System.Guid> SecManager { get; set; }
        public Nullable<System.Guid> Trainer { get; set; }
        public Nullable<bool> TypeManager { get; set; }
        public Nullable<bool> TypeAuditor { get; set; }
        public Nullable<bool> TypeBDR { get; set; }
        public Nullable<bool> TypeAcctRep { get; set; }
        public Nullable<bool> TypeColRep { get; set; }
        public Nullable<bool> TypeTrainer { get; set; }
        public string MenuAdminPosit { get; set; }
    
        public virtual aspnet_Membership aspnet_Membership { get; set; }
        public virtual aspnet_Profile aspnet_Profile { get; set; }
        public virtual ICollection<aspnet_Roles> aspnet_Roles { get; set; }
    }
}
