//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salt_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FutureBenefitsEntry
    {
        public System.Guid pkid { get; set; }
        public Nullable<System.Guid> ClientPKID { get; set; }
        public string Installment { get; set; }
        public Nullable<decimal> OriginalAmount { get; set; }
        public Nullable<decimal> Adjusted { get; set; }
        public string CollectionNote { get; set; }
        public Nullable<decimal> AmountRecovered { get; set; }
        public string BatchNumber { get; set; }
        public string Notes { get; set; }
    }
}
