//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salt_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuContractConfirm
    {
        public int ContractConfirmKey { get; set; }
        public Nullable<int> ContractConfirmID { get; set; }
        public string ContractConfirmDesc { get; set; }
    }
}
