//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salt_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuContractStatu
    {
        public int ContractStautsKey { get; set; }
        public Nullable<int> ContractStatusID { get; set; }
        public string ContractStatusDesc { get; set; }
    }
}
