//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salt_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefundEntry
    {
        public System.Guid PKID { get; set; }
        public System.Guid ClientPKID { get; set; }
        public System.Guid VendorPKID { get; set; }
        public Nullable<decimal> AmountIdentified { get; set; }
        public System.Guid StateIdentified { get; set; }
        public Nullable<decimal> Adjusted { get; set; }
        public System.Guid CollectionNote { get; set; }
        public Nullable<decimal> AmountRecovered { get; set; }
        public string BatchNumber { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> RecoveryType { get; set; }
        public Nullable<decimal> LeftToRecover { get; set; }
    }
}
