//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salt_web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class salt_entities : DbContext
    {
        public salt_entities()
            : base("name=salt_entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<MenuUSState> MenuUSStates { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<MenuPayNote> MenuPayNotes { get; set; }
        public virtual DbSet<MenuContractStatu> MenuContractStatus { get; set; }
        public virtual DbSet<MenuContractConfirm> MenuContractConfirms { get; set; }
        public virtual DbSet<MenuAssigned> MenuAssigneds { get; set; }
        public virtual DbSet<MenuRecoveryType> MenuRecoveryTypes { get; set; }
        public virtual DbSet<MenuTravel> MenuTravels { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<WorkWeb> WorkWebs { get; set; }
        public virtual DbSet<MenuRental> MenuRentals { get; set; }
        public virtual DbSet<MenuContractType> MenuContractTypes { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<RefundEntry> RefundEntries { get; set; }
        public virtual DbSet<MenuCollectionNote> MenuCollectionNotes { get; set; }
        public virtual DbSet<CreditInterestReveived> CreditInterestReveiveds { get; set; }
        public virtual DbSet<StateRefundEntry> StateRefundEntries { get; set; }
        public virtual DbSet<FutureBenefitsEntry> FutureBenefitsEntries { get; set; }
        public virtual DbSet<CustomerPaymentsEntry> CustomerPaymentsEntries { get; set; }
    }
}
