//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salt_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateRefundEntry
    {
        public System.Guid pkid { get; set; }
        public Nullable<System.Guid> ClientPKID { get; set; }
        public string BatchDescription { get; set; }
        public Nullable<decimal> AmountSubmitted { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> DeniedAdjusted { get; set; }
        public Nullable<decimal> BalanceState { get; set; }
        public string BatchNumber { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateMTSMailed { get; set; }
    }
}
